---
title: "PITCounts"
author: "Adkison"
date: "4/21/2020"
output: 
  html_document:
      toc: true
      toc_float: true
      toc_depth: 4
---
 

#### Jour 405v, Jour 5003, Spring 2020    

#### Advanced Reporting and Data Analysis

#### Reporting on Homelessness in Northwest Arkansas

--------------------------------------------------------------------
# Analysis of PIT Counts for Northwest Arkansas, Arkansas, and the U.S.


Load libraries.
```{r}
library(rio)
library(tidyverse)
library(ggplot2)
library(dplyr)
```

Graphic #1: NWA vs. Arkansas

Load data
```{r}
StateData <- rio::import("https://github.com/michaeladkison/PITCounts/blob/master/Raw%20data.xlsx?raw=true", which = "NWA vs. State")
```

Making the State comparison graphic
```{r}
ggplot(data= StateData) +
  geom_bar(mapping = aes(x= Year, y= NWA), stat="identity", fill = "green") +
  geom_line(mapping= aes(x= Year, y= State), stat="identity", color="blue", fill= "blue") +
  scale_x_continuous(breaks=c(2007:2019), name = "Year") +
   scale_y_continuous(limits=c(0,5000), name = "Number of Homeless Individuals") +
  geom_text(aes(label= NWA, x= Year, y= NWA), hjust=.5, vjust=0) +
  geom_text(aes(label= State, x= Year, y= State), hjust=.5, vjust=-1.5)+
  geom_text(label= "Arkansas",
            x= 2007, y= 2850) +
   geom_text(label= "Northwest Arkansas",
            x= 2008, y= 750) +
  labs(title = "Homeless Point in Time Counts for Northwest Arkansas and the State of Arkansas",
       subtitle= "Data from HUD Exchange",
       caption= "Graphic by Michael Adkison",
       y = "Reported Number of Homeless Individuals, 4-21-2020",
       x = "Year")
  
```
Save the file.

```{r}

ggsave("Adkison_State_Homeless.png",device = "png",width=9,height=6, dpi=800)
```

Graphic #2: NWA Unsheltered

Load data
```{r}
Unsheltered <- rio::import("https://github.com/michaeladkison/PITCounts/blob/master/Raw%20data.xlsx?raw=true", which = "NWA Unsheltered")
```

Building the stacked bar graph

```{r}
ggplot(data=Unsheltered) +
  geom_bar(mapping=aes(x= Year, y= NWA, fill= "green"), stat= "identity") +
  geom_bar(mapping=aes(x= Year, y= NWA_Unsheltered, , fill= "blue"), stat= "identity") +
  scale_fill_identity(guide = "legend") +
  scale_fill_identity(name = "Housing Status",
                          breaks = c("green", "blue"),
                          labels = c("Total Homeless", "Unsheltered Homeless"),
                          guide = "legend") +
  scale_x_continuous(breaks=c(2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019)) +
  geom_text(aes(label= NWA, x= Year, y= NWA), hjust=.5, vjust=0) +
  geom_text(aes(label= NWA_Unsheltered, x= Year, y= NWA_Unsheltered), hjust=.5, vjust=-.5) +
  labs(title = "Unsheltered and Total Homeless Population in Northwest Arkansas",
       subtitle= "Point in Time Count Data from HUD Exchange",
       caption= "Graphic by Michael Adkison, 4-21-20",
       y = "Number of Homeless Individuals",
       x = "Year")
```

Save the file.
```{r}

ggsave("Adkison_Sheltered_Unsheltered.png",device = "png",width=9,height=6, dpi=800)
```